import argparse
import cmd2

from server.core.server_state import command_guard, ServerFSM
from server.utils.logger import get_logger


logger = get_logger("acquisition_commands")


########################
# ACQUISITION COMMANDS #
########################


def _add_common_acquisition_arguments(parser: argparse.ArgumentParser) -> None:
    """
    Add arguments shared by all acquisition trigger modes.
    """

    parser.add_argument(
        "--duration",
        type=float,
        default=None,
        help=(
            "Acquisition duration in seconds. "
            "If omitted, run until stopped."
        ),
    )

    parser.add_argument(
        "--type",
        dest="acq_type",
        type=str,
        default="test",
        help=(
            "Acquisition type, e.g. test, pedestal, spe, gain, threshold."
        ),
    )

    parser.add_argument(
        "--suffix",
        type=str,
        default="",
        help="Suffix for the output file name.",
    )

    parser.add_argument(
        "--run-id",
        type=str,
        default=None,
        help=(
            "Optional run ID. "
            "If omitted, an automatic acq_N folder is created."
        ),
    )

    parser.add_argument(
        "--file-format",
        type=str,
        choices=["csv", "bin"],
        default="csv",
        help="Output file format. Default: csv.",
    )


acquisition_parser = argparse.ArgumentParser()

acquisition_subparsers = acquisition_parser.add_subparsers(
    dest="command",
    required=True,
)


#####################
# ACQUISITION START #
#####################

start_parser = acquisition_subparsers.add_parser(
    "start",
    help="Start acquisition",
)

trigger_mode_subparsers = start_parser.add_subparsers(
    dest="trigger_mode",
    required=True,
)


################
# SELF TRIGGER #
################

self_trigger_parser = trigger_mode_subparsers.add_parser(
    "self",
    help="Start acquisition in self-trigger mode",
)

_add_common_acquisition_arguments(self_trigger_parser)


####################
# EXTERNAL TRIGGER #
####################

external_trigger_parser = trigger_mode_subparsers.add_parser(
    "external",
    help="Start acquisition using the external trigger",
)

_add_common_acquisition_arguments(external_trigger_parser)

external_trigger_parser.add_argument(
    "--input",
    dest="trigger_input",
    type=str,
    choices=["differential", "single-ended"],
    default="differential",
    help=(
        "External trigger electrical input type. "
        "Default: differential."
    ),
)

external_trigger_parser.add_argument(
    "--polarity",
    type=str,
    choices=["default", "inverted"],
    default="default",
    help=(
        "External trigger polarity. "
        "Default: default."
    ),
)

external_trigger_parser.add_argument(
    "--window-ns",
    type=int,
    default=400,
    help=(
        "Trigger acquisition window in ns. "
        "The hardware resolution is 5 ns. "
        "Default: 400 ns."
    ),
)

external_trigger_parser.add_argument(
    "--delay-ns",
    type=int,
    default=800,
    help=(
        "Delay before opening the trigger window, in ns. "
        "The hardware resolution is 5 ns. "
        "Default: 800 ns."
    ),
)

external_trigger_parser.add_argument(
    "--save-auto",
    action="store_true",
    help=(
        "Also save auto-trigger events while the external trigger "
        "is the main trigger source."
    ),
)


################
# AUTO TRIGGER #
################

auto_trigger_parser = trigger_mode_subparsers.add_parser(
    "auto",
    help="Start acquisition using the auto-trigger",
)

auto_logic_subparsers = auto_trigger_parser.add_subparsers(
    dest="auto_logic",
    required=True,
)


#########################
# AUTO TRIGGER MAJORITY #
#########################

majority_parser = auto_logic_subparsers.add_parser(
    "majority",
    help="Auto-trigger generated by channel multiplicity",
)

_add_common_acquisition_arguments(majority_parser)

majority_parser.add_argument(
    "--multiplicity",
    type=int,
    required=True,
    choices=range(1, 8),
    metavar="N",
    help=(
        "Required channel multiplicity, from 1 to 7. "
        "Example: --multiplicity 2 triggers when at least "
        "two channels are active."
    ),
)

majority_parser.add_argument(
    "--window-ns",
    type=int,
    default=400,
    help=(
        "Trigger acquisition window in ns. "
        "The hardware resolution is 5 ns. "
        "Default: 400 ns."
    ),
)

majority_parser.add_argument(
    "--delay-ns",
    type=int,
    default=800,
    help=(
        "Delay before opening the trigger window, in ns. "
        "The hardware resolution is 5 ns. "
        "Default: 800 ns."
    ),
)

majority_parser.add_argument(
    "--save-external",
    action="store_true",
    help=(
        "Also save external-trigger events while auto-trigger "
        "is the main trigger source."
    ),
)


######################
# AUTO TRIGGER EXACT #
######################

exact_parser = auto_logic_subparsers.add_parser(
    "exact",
    help="Auto-trigger generated only by a specific channel combination",
)

_add_common_acquisition_arguments(exact_parser)

exact_parser.add_argument(
    "--channels",
    type=str,
    required=True,
    help=(
        "Exact auto-trigger channel combination. "
        'Use a comma-separated list, e.g. "0,1,4".'
    ),
)

exact_parser.add_argument(
    "--window-ns",
    type=int,
    default=400,
    help=(
        "Trigger acquisition window in ns. "
        "The hardware resolution is 5 ns. "
        "Default: 400 ns."
    ),
)

exact_parser.add_argument(
    "--delay-ns",
    type=int,
    default=800,
    help=(
        "Delay before opening the trigger window, in ns. "
        "The hardware resolution is 5 ns. "
        "Default: 800 ns."
    ),
)

exact_parser.add_argument(
    "--save-external",
    action="store_true",
    help=(
        "Also save external-trigger events while auto-trigger "
        "is the main trigger source."
    ),
)


####################
# ACQUISITION STOP #
####################

stop_parser = acquisition_subparsers.add_parser(
    "stop",
    help="Stop acquisition",
)


###################
# FSM PER COMMAND #
###################

COMMAND_FSM_MAP = {
    "start": {ServerFSM.READY},
    "stop": {
        ServerFSM.ACQUIRING,
        ServerFSM.FINALIZING,
        ServerFSM.READY,
    },
}


@cmd2.with_argparser(acquisition_parser)
@cmd2.with_category("Acquisition Commands")
@command_guard(
    [
        ServerFSM.READY,
        ServerFSM.ACQUIRING,
        ServerFSM.FINALIZING,
    ]
)
def do_acquisition(self, args: argparse.Namespace) -> None:
    """
    Acquisition commands:
        acquisition start self
        acquisition start external
        acquisition start auto majority
        acquisition start auto exact
        acquisition stop
    """

    current_state = self.server_state.get_server_state()
    allowed_states = COMMAND_FSM_MAP[args.command]

    if current_state not in allowed_states:
        allowed_names = ", ".join(
            sorted(state.value for state in allowed_states)
        )

        self.poutput(
            f"Cannot run 'acquisition {args.command}' while server is "
            f"'{current_state.value}'. Allowed states: {allowed_names}."
        )

        logger.error(
            f"Acquisition command '{args.command}' blocked: "
            f"state={current_state.value}"
        )
        return

    if args.command == "start":
        self.acquisition_orchestrator.start(args)
        return

    if args.command == "stop":
        self.acquisition_orchestrator.stop()
        return

